<html>   <!-- "standard" include file -->
<head>
<title>
The Collective - MontaVista Build Log Viewer
</title>
</head>
<!--  Let's try various colors.... -->

<body text="#000000" bgcolor="#999999" link="#000000" vlink="#000000" alink="#000000"> <!-- a friendly, light (ferret) blue -->

<a href=http://collective.sh.mvista.com/collective.shtml><img src=/images/halloween-pumpkin.jpg alt="Collective" align=right border=0></a>

<a href=http://collective.sh.mvista.com/collective.shtml>Collective Home</a>&nbsp; &nbsp; -  &nbsp; &nbsp;

<a href=/LogList.shtml>Build Logs</a>&nbsp; &nbsp; -  &nbsp; &nbsp;

<a href=/logs/CurrentBuild/build.shtml>Current Build</a>&nbsp; &nbsp; -  &nbsp; &nbsp;
<a href=http://wiki.mvista.com/thebazaar/bin/view/Engineering/BuildRequests>Build Request</a> &nbsp; &nbsp; -  &nbsp; &nbsp;
<!--
<a href=/BuildRequest.shtml>Build Request</a> &nbsp; &nbsp; -  &nbsp; &nbsp;
<a href=/BuildRequestAdv.shtml>Advanced Build Request</a> &nbsp; &nbsp; -  &nbsp; &nbsp;
<a href=/cgi-bin/ViewRequest>Build Queue</a> &nbsp; &nbsp; -  &nbsp; &nbsp;
-->
<a href=http://wiki.sh.mvista.com/thebazaar2/bin/view/Engineering/BuildSchedule>Build Schedule</a> &nbsp; &nbsp; -  &nbsp; &nbsp;
<a href=http://ferret.mvista.com/Ferret/Welcome.html>Ferret Home</a>

<hr>

