#!/usr/bin/env python
import os, commands, sys

for file in os.listdir(os.getcwd()):
	if os.path.isdir(file):
		continue
	if os.path.exists(file + '.md5'):
		fp = open(file + '.md5')
		md5sum = fp.readline().strip()
		fp.close()
		file_md5sum = commands.getoutput('md5sum %s' % file).split('\n')[0].split(' ')[0]
		sys.stdout.write('Checking %s...' % file)
		if md5sum == file_md5sum:
			sys.stdout.write('OK.')
		else:
			sys.stdout.write('FAILED!')
		sys.stdout.write('\n')
	

