# generic disk configuration for one small disk
# disk size from 500Mb up to what you can buy today
#
# <type> <mountpoint> <size in mb> [mount options]     [;extra options]

disk_config disk1
primary  /             3000-      rw,errors=remount-ro ;-c -j ext3
logical  swap          1000      rw                   
