#! /bin/sh

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    node*)
	echo "BUILD FAIBASE DHCPC" ;;
#Engineering class defined by hyost name
    scratch*)
    	echo "SCRATCH FAIBASE DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 



exit 0
