#!/bin/bash

# $1 is logdir
# $2 is log file
# $3 is arch

if [ "$#" -eq 0 ]; then
  echo "Usage: getNotBuilt <logdir> <log file> <arch>"
  exit 1
fi

logdir="$1"
logfile="$2"
arch="$3"

if [ "$(cat $logdir/$logfile | grep "BUILD ERROR" | grep -v BUILDCORE | grep -v BUILD\/)" != "" ]; then
  echo "$logfile:" >> $logdir/NotBuilt-"$arch".log
  cat $logdir/$logfile | grep "BUILD ERROR" | grep -v BUILDCORE | grep -v BUILD\/ >> $logdir/NotBuilt-"$arch".log
  echo " " >> $logdir/NotBuilt-"$arch".log
fi
