#!/usr/bin/python


import sys
import re
import os
import string

#emailing
import smtplib
from email.MIMEText import MIMEText


for line in os.popen("df -h /home").readlines():
  extracted = re.search(r'(\d+)%', line)
  if extracted != None:
    break 

temp1 = string.atoi(extracted.group(1))
if temp1 >= 75:
  #Standard SMTP SETUP
  smtpObject = smtplib.SMTP()
  mailMsg    = MIMEText('Daily status message generated by diskUsage.py')
  mailMsg['From'] = "build@mvista.com"  
  mailMsg['To'] = "build_status@mvista.com"
  mailMsg['Subject'] = "/home/build operating at: " + extracted.group(1) + "% capacity"
  #Send Message
  smtpObject.connect('mail.mvista.com')
  smtpObject.sendmail('cvanarsdall@mvista.com','build_status@mvista.com', mailMsg.as_string())
  smtpObject.close()
