#!/bin/bash

hn="$(hostname -s)"

if [ "$hn" = "node-7" ]; then
  archs="arm_sa_be"
elif [ "$hn" = "node-8" ]; then
  archs="arm_sa_le"
elif [ "$hn" = "node-9" ]; then
  archs="arm_xscale_be"
elif [ "$hn" = "node-18" ]; then
  archs="arm_xscale_le mips_sb1_fp_be"
elif [ "$hn" = "node-10" ]; then
  archs="mips_fp_be"
elif [ "$hn" = "node-19" ]; then
  archs="mips_fp_le"
elif [ "$hn" = "node-11" ]; then
  archs="mips_lexra_fp_be"
elif [ "$hn" = "node-20" ]; then
  archs="arm_720t_le"
elif [ "$hn" = "node-12" ]; then
  archs="mips_sony_fp_be"
elif [ "$hn" = "node-21" ]; then
  archs="mips_sony_fp_le"
elif [ "$hn" = "node-22" ]; then
  archs="ppc_405 ppc_74xx"
elif [ "$hn" = "node-23" ]; then
  archs="ppc_7xx ppc_82xx"
elif [ "$hn" = "node-24" ]; then
  archs="ppc_8xx arm_920t_le"
elif [ "$hn" = "node-25" ]; then
  archs="sh_sh3_be sh_sh3_le"
elif [ "$hn" = "node-26" ]; then
  archs="sh_sh4_be sh_sh4_le"
elif [ "$hn" = "node-27" ]; then
  archs="x86_pentium3"
elif [ "$hn" = "node-31" ]; then
  archs="x86_486"
elif [ "$hn" = "node-28" ]; then
  archs="x86_586"
elif [ "$hn" = "node-29" ]; then
  archs="x86_crusoe"
elif [ "$hn" = "node-30" ]; then
  archs="x86_pentium2"
fi
archs="mips_fp_be mips_fp_le mips_lexra_fp_be"

apps="gcc"
#type="cross"
type="target"
bug="1-32IK1"

for p in $apps; do
  for a in $archs; do
     rm -rf /opt/hardhat/*
     cp -a /var/lib/rpm /opt/hardhat/rpmdb
     if [ "$a" = "mips_sony_fp_be" ]; then
       rpmdir="/mvista/release_area/mvl2.1.0_sony_be"
     elif [ "$a" = "mips_sb1_fp_be" ]; then
       rpmdir="/mvista/release_area/mvl2.1.0a"
     elif [ "$a" = "arm_xscale_be" ]; then
       rpmdir="/mvista/release_area/mvl2.1.0_brh"
     else
       rpmdir="/mvista/release_area/mvl2.1.0-orig"
     fi
     cd "$rpmdir"/host/common/optional
     rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     cd "$rpmdir"/host/common
     rpm --dbpath /opt/hardhat/rpmdb -i *file* *ldd* *python* *setperm* *targetconf*
     cd "$rpmdir"/host/cluster
     rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     cd "$rpmdir"/$a/cross/common
     ls | grep -v glib | xargs rpm --dbpath /opt/hardhat/rpmdb -i 
     cd "$rpmdir"/$a/cross/cluster
     if [ "$p" = "gcc" ] || [ "$p" = "glibc" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i *binutils* *hardhatutils* *ksymoops* *ldd* *linux86*
     elif [ "$p" = "gdb" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i *binutils* *hardhatutils* *ksymoops* *ldd* *linux86* *gcc* *cpp* *g++*
       if [ "$type" = "target" ]; then
         rpm --dbpath /opt/hardhat/rpmdb -i /mvista/release_area/mvl2.1.0-updates/gdb/$a/cross/cluster/*gdb*
       fi
     else
       ls | grep -v gdb | xargs rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     fi
     cd "$rpmdir"/$a/target
     if [ "$p" = "glibc" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers*
       if [ "$a" = "mips_sb1_fp_be" ]; then
         rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch /mvista/release_area/mvl2.1.0-updates/gcc-bootstrap/*sb1*
       fi
     elif [ "$p" = "gcc" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers* *binutils* *glibc* *ncurses*
     else
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers* *binutils* *glibc* *ncurses* *gcc* *cpp* *g++* *libstdc++* *protoize* *flex* *libwrap* *zlib* *libpam* *libtool*
     fi
     cd ~/toolchain/$p
     if [ "$type" = "cross" ]; then
       if [ "$p" = "gcc" ]; then
         ~/bin/mkappnoclean `pwd` mvl2.1.0 $a cross-"$p"2.95.3 /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl2.1.0-updates/$p-$bug/cross-cluster-$a.log 2>&1
       else
         ~/bin/mkappnoclean `pwd` mvl2.1.0 $a cross-$p /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl2.1.0-updates/$p-$bug/cross-cluster-$a.log 2>&1
       fi
       mkdir -p /mvista/dev_area/mvl2.1.0-updates/$p-$bug/$a/cross/cluster
       mkdir -p /mvista/dev_area/mvl2.1.0-updates/$p-$bug/SRPMS
       cp -f SRPMS/* /mvista/dev_area/mvl2.1.0-updates/$p-$bug/SRPMS
       cp RPMS/i386/*$a* /mvista/dev_area/mvl2.1.0-updates/$p-$bug/$a/cross/cluster
     elif [ "$type" = "target" ]; then
       if [ "$p" = "gcc" ]; then
         rpm --dbpath /opt/hardhat/rpmdb -ivh /mvista/dev_area/mvl2.1.0-updates/$p-$bug/$a/cross/cluster/*.rpm
         ~/bin/mkappnoclean `pwd` mvl2.1.0 $a target-$p-$a /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl2.1.0-updates/$p-$bug/target-cluster-$a.log 2>&1
       else
         ~/bin/mkappnoclean `pwd` mvl2.1.0 $a target-$p /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl2.1.0-updates/$p-$bug/target-cluster-$a.log 2>&1
       fi
       mkdir -p /mvista/dev_area/mvl2.1.0-updates/$p-$bug/$a/target
       mkdir -p /mvista/dev_area/mvl2.1.0-updates/$p-$bug/SRPMS
       cp -f SRPMS/* /mvista/dev_area/mvl2.1.0-updates/$p-$bug/SRPMS
       cp RPMS/$a/*$a* /mvista/dev_area/mvl2.1.0-updates/$p-$bug/$a/target
     fi
  done
done
