#!/bin/bash
apps="$1"
type="$2"
bug="$3"

hn="$(hostname -s)"
if [ "$hn" = "node-6" ]; then
  archs="sh_sh3_le"
elif [ "$hn" = "node-7" ]; then
  archs="x86_pentium2"
elif [ "$hn" = "node-8" ]; then
  archs="mips_nfp_le"
elif [ "$hn" = "node-9" ]; then
  archs="ppc_74xx"
elif [ "$hn" = "node-10" ]; then
  archs="sh_sh3_be"
elif [ "$hn" = "node-11" ]; then
  archs="mips_fp_be"
elif [ "$hn" = "node-12" ]; then
  archs="sh_sh4_be"
elif [ "$hn" = "node-17" ]; then
  archs="sh_sh4_le"
elif [ "$hn" = "node-18" ]; then
  archs="x86_486"
elif [ "$hn" = "node-19" ]; then
  archs="x86_pentium3"
elif [ "$hn" = "node-20" ]; then
  archs="arm_920t_le"
elif [ "$hn" = "node-21" ]; then
  archs="arm_xscale_le"
elif [ "$hn" = "node-22" ]; then
  archs="arm_sa_le"
elif [ "$hn" = "node-23" ]; then
  archs="mips_fp_le"
elif [ "$hn" = "node-24" ]; then
  archs="ppc_7xx"
elif [ "$hn" = "node-25" ]; then
  archs="ppc_405"
elif [ "$hn" = "node-26" ]; then
  archs="arm_sa_be"
elif [ "$hn" = "node-27" ]; then
  archs="arm_720t_le"
elif [ "$hn" = "node-28" ]; then
  archs="x86_crusoe x86_586"
elif [ "$hn" = "node-29" ]; then
  archs="arm_xscale_be"
elif [ "$hn" = "node-30" ]; then
  archs="xtensa_linux_le xtensa_linux_be"
elif [ "$hn" = "node-31" ]; then
  archs="ppc_8xx ppc_82xx"
fi
#archs="arm_720t_le arm_920t_le arm_sa_be arm_sa_le arm_xscale_be arm_xscale_le mips_fp_be mips_fp_le ppc_405 ppc_74xx ppc_7xx ppc_82xx ppc_8xx sh_sh3_be sh_sh3_le sh_sh4_be sh_sh4_le x86_486 x86_586 x86_crusoe x86_pentium2 x86_pentium3 mips_nfp_le xtensa_linux_be xtensa_linux_le"

for p in $apps; do
  for a in $archs; do
    rm -rf /opt/hardhat/*
    cp -a /var/lib/rpm /opt/hardhat/rpmdb
    if [ "$a" = "mips_nfp_le" ]; then
      rpmdir="/mvista/release_area/mvl300_x225"
    elif [ "$a" = "xtensa_linux_be" ] || [ "$a" = "xtensa_linux_le" ]; then
       rpmdir="/mvista/release_area/mvl300_xtensa"
    else
      rpmdir="/mvista/release_area/mvl3.0.0"
    fi
    cd "$rpmdir"/host/common/optional/
    rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
    cd ..
    rpm --dbpath /opt/hardhat/rpmdb -i *file* *ldd* *python* *setperm* *targetconf*
    if [ "$a" = "xtensa_linux_be" ] || [ "$a" = "xtensa_linux_le" ]; then
      rpm --dbpath /opt/hardhat/rpmdb -i *rpmconfig* *platformtest*
    fi
    cd ../cluster
    rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
    if [ "$p" = "ramdisk" ]; then
      cd /home/build/userland/e2fsprogs
      rpm --dbpath /opt/hardhat/rpmdb -i RPMS/i386/*.rpm
    fi
    cd "$rpmdir"/$a/cross/common
    rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
    cd ../cluster
    if [ "$p" = "gcc" ] && [ "$type" = "cross" ]; then
      rpm --dbpath /opt/hardhat/rpmdb -i *binutils* *hardhatutils* *ksymoops* *ldd* *linux86*
    else
      rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
    fi
    cd ../../target
    if [ "$p" = "glibc" ]; then
      rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers*
    elif [ "$p" = "gcc" ]; then
      rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers* *binutils* *glibc* *ncurses*
    elif [ "$p" = "ramdisk" ]; then
      rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *.rpm
    else
      ls *.rpm | grep -v $p | xargs rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch --nodeps
    fi
    cd ~/userland/$p
    if [ "$type" = "cross" ]; then
      if [ "$p" = "gcc" ]; then
        ~/bin/mkappnoclean `pwd` mvl3.0.0 $a cross-"$p"3.2 /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl3.0.0-updates/$p-$bug/$a.log 2>&1
      else
        ~/bin/mkappnoclean `pwd` mvl3.0.0 $a cross-$p /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl3.0.0-updates/$p-$bug/$a.log 2>&1
      fi
      if [ -d RPMS/i386 ]; then
        mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p-$bug/$a/cross/cluster
        cp RPMS/i386/* /mvista/dev_area/mvl3.0.0-updates/$p-$bug/$a/cross/cluster
      elif [ -d RPMS/noarch ]; then
        mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p-$bug/$a/cross/common
        cp RPMS/noarch/*$a* /mvista/dev_area/mvl3.0.0-updates/$p-$bug/$a/cross/common
      fi
    elif [ "$type" = "target" ]; then
      ~/bin/mkappnoclean `pwd` mvl3.0.0 $a target-$p /opt/hardhat/rpmdb ~/.perpmrc rpm > /mvista/dev_area/logs/mvl3.0.0-updates/$p-$bug/$a.log 2>&1
      mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p-$bug/$a/target
      mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p-$bug/SRPMS
      cp -f SRPMS/* /mvista/dev_area/mvl3.0.0-updates/$p-$bug/SRPMS
      cp RPMS/$a/* /mvista/dev_area/mvl3.0.0-updates/$p-$bug/$a/target
    fi
    mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p-$bug/SRPMS
    cp -f SRPMS/* /mvista/dev_area/mvl3.0.0-updates/$p-$bug/SRPMS
  done
done
