#!/bin/bash

hn="$(hostname -s)"
if [ "$hn" = "node-7" ]; then
  archs="mips_fp_be"
elif [ "$hn" = "node-8" ]; then
  archs="ppc_74xx"
elif [ "$hn" = "node-9" ]; then
  archs="ppc_82xx"
elif [ "$hn" = "node-10" ]; then
  archs="sh_sh4_le"
elif [ "$hn" = "node-11" ]; then
  archs="arm_920t_le"
elif [ "$hn" = "node-12" ]; then
  archs="arm_xscale_le"
elif [ "$hn" = "node-18" ]; then
  archs="sh_sh3_be"
elif [ "$hn" = "node-19" ]; then
  archs="sh_sh4_be"
elif [ "$hn" = "node-20" ]; then
  archs="x86_486"
elif [ "$hn" = "node-22" ]; then
  archs="x86_pentium3"
elif [ "$hn" = "node-23" ]; then
  archs="arm_sa_le"
elif [ "$hn" = "node-24" ]; then
  archs="mips_fp_le"
elif [ "$hn" = "node-25" ]; then
  archs="ppc_405 ppc_7xx"
elif [ "$hn" = "node-26" ]; then
  archs="arm_720t_le arm_sa_be"
elif [ "$hn" = "node-21" ]; then
  archs="x86_crusoe"
elif [ "$hn" = "node-27" ]; then
  archs="arm_xscale_be"
elif [ "$hn" = "node-28" ]; then
  archs="ppc_8xx"
elif [ "$hn" = "node-29" ]; then
  archs="x86_586"
elif [ "$hn" = "node-30" ]; then
  archs="sh_sh3_le"
elif [ "$hn" = "node-31" ]; then
  archs="x86_pentium2"
fi

apps="ramdisk"
type="cross"

for p in $apps; do
  if [ -d "~/userland/$p/RPMS" ]; then
    m -rf ~/userland/$p/RPMS 
  fi
  if [ -d "~/userland/$p/SRPMS" ]; then
    rm -rf ~/userland/$p/SRPMS 
  fi
  mkdir -p /mvista/dev_area/logs/mvl3.0.0-updates/$p
  for a in $archs; do
     rm -rf /opt/hardhat/*
     cp -a /var/lib/rpm /opt/hardhat/rpmdb
     cd /mvista/release_area/mvl2.1.0/host/common/optional/
     rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     cd ..
     rpm --dbpath /opt/hardhat/rpmdb -i *file* *ldd* *python* *setperm* *targetconf*
     cd ../cluster
     rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     cd ../../$a/cross/common
     rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     cd ../cluster
     if [ "$p" = "gcc" ] && [ "$type" = "cross" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i *binutils* *hardhatutils* *ksymoops* *ldd* *linux86*
     else
       rpm --dbpath /opt/hardhat/rpmdb -i *.rpm
     fi
     cd ../../target
     if [ "$p" = "glibc" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers*
     elif [ "$p" = "gcc" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers* *binutils* *glibc* *ncurses*
     elif [ "$p" = "ramdisk" ]; then
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *.rpm
     else
       rpm --dbpath /opt/hardhat/rpmdb -i --ignorearch *filesystem* *kernel-headers* *binutils* *glibc* *ncurses* *gcc* *cpp* *g++* *libstdc++* *protoize* *flex* *libwrap* *zlib* *libpam* *libtool*
     fi
     cd ~/userland/$p
     if [ "$type" = "cross" ]; then
       if [ "$p" = "gcc" ]; then
         ~/bin/mkappnoclean `pwd` mvl3.0.0 $a cross-"$p"3.2 /opt/hardhat/rpmdb ~/.perpmrc > /mvista/dev_area/logs/mvl3.0.0-updates/$p/$a.log 2>&1
       else
         ~/bin/mkappnoclean `pwd` mvl3.0.0 $a cross-$p /opt/hardhat/rpmdb ~/.perpmrc > /mvista/dev_area/logs/mvl3.0.0-updates/$p/$a.log 2>&1
       fi
       if [ -d RPMS/i386 ]; then
         mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p/$a/cross/cluster
         cp RPMS/i386/* /mvista/dev_area/mvl3.0.0-updates/$p/$a/cross/cluster
       elif [ -d RPMS/noarch ]; then
         mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p/$a/cross/common
         cp RPMS/noarch/* /mvista/dev_area/mvl3.0.0-updates/$p/$a/cross/common
       fi
       mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p/SRPMS
       cp -f SRPMS/* /mvista/dev_area/mvl3.0.0-updates/$p/SRPMS
     elif [ "$type" = "target" ]; then
       ~/bin/mkappnoclean `pwd` mvl3.0.0 $a target-$p /opt/hardhat/rpmdb ~/.perpmrc > /mvista/dev_area/logs/mvl3.0.0-updates/$p/$a.log 2>&1
       mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p/$a/target
       mkdir -p /mvista/dev_area/mvl3.0.0-updates/$p/SRPMS
       cp -f SRPMS/* /mvista/dev_area/mvl3.0.0-updates/$p/SRPMS
       cp RPMS/$a/* /mvista/dev_area/mvl3.0.0-updates/$p/$a/target
     fi
  done
done
