#!/bin/bash

nodes="node-7 node-8 node-9 node-18 node-19 node-20 node-21 node-22 node-23 node-24 node-25 node-26 node-27 node-28 node-29 node-30 node-31"

for n in $nodes; do
  ssh $n "cd /home/build/userland; ./go" &
  #ssh $n "hostname -s"
done
