#!/bin/bash

# This script

# args:
# 1- application or tool to build
# 2- The bug or defect id (you must have a defect number)
# 3- type of build -- i.e. target, cross or if app is cross and no arch use cross-noarch

if [ "$#" != "3" ]; then
  echo "Usage: $0 "<application or tool>" <bug-id> <type>"
  echo "<application or tool> The tool chain app you are rebuilding"
  echo "<bug-id> The defect number used to check the fixes into cvs"
  echo "<type> This is the type of tool.. a target or cross"
  exit 1
fi

hn="$(hostname -s)"

if [ "$hn" = "node-1" ]; then
  archs="x86_pentium2"
elif [ "$hn" = "node-2" ]; then
  archs="x86_pentium4" 
elif [ "$hn" = "node-3" ]; then
  archs="x86_pentium3"
fi

apps="$1"
bugid="$2"
# if app is cross and noarch, use target="cross-noarch"
# otherwise use "cross"
type="$3"
b=$bugid
for p in $apps; do
  for a in $archs; do
     rm -rf /opt/mvlcge/*
     cp -a /var/lib/rpm /opt/mvlcge/rpmdb
     cd /mvista/dev_area/mvlcge210_rebuilt_hostkernel/
     rpm -ihv *.rpm --dbpath /opt/mvlcge/rpmdb
     cd /mvista/release_area/mvlcge2.1.0/host/common/optional/
     ls | grep -v kernel | xargs  rpm -ihv --dbpath /opt/mvlcge/rpmdb 
     cd ..
     rpm -ihv *file* *ldd* *python* *setperm* *targetconf* --dbpath /opt/mvlcge/rpmdb
     cd ../cluster
     rpm -ihv *.rpm --dbpath /opt/mvlcge/rpmdb
     cd ../../$a/cross/common
     ls | grep -v glib | xargs rpm -ihv --dbpath /opt/mvlcge/rpmdb
     cd ../cluster
     if [ "$p" = "gcc" ] && [ "$type" = "cross" ]; then
      rpm -ihv *binutils* *hardhatutils* *ksymoops* *ldd* *linux86* --dbpath /opt/mvlcge/rpmdb
     else
       ls | grep -v gdb | xargs rpm -ihv --dbpath /opt/mvlcge/rpmdb
     fi
     cd ../../target
     if [ "$p" = "glibc" ]; then
       rpm -ihv --ignorearch *filesystem* *kernel-headers* --dbpath /opt/mvlcge/rpmdb
     elif [ "$p" = "gcc" ]; then
       rpm -ihv --ignorearch *filesystem* *kernel-headers* *binutils* *glibc* *ncurses* --dbpath /opt/mvlcge/rpmdb
     elif [ "$p" = "apache" ]; then
       ls *.rpm | grep -v $p | xargs rpm --dbpath /opt/mvlcge/rpmdb -ihv --ignorearch --nodeps
     else
       ls *.rpm | grep -v $p | xargs rpm --dbpath /opt/mvlcge/rpmdb -ihv --ignorearch --nodeps
     fi	
     cd ~/cge-userland/$p
     if [ "$type" = "cross" ]; then
      if [ "$p" = "gcc" ]; then
       ~/bin/mk3.0appnoclean `pwd` mvlcge2.1.0 $a cross-"$p"2.95.3 /opt/mvlcge/rpmdb ~/.cgerpmrc rpm > /mvista/dev_area/logs/mvlcge2.1.0-updates/$p-$b/$a.log 2>&1
      else
       ~/bin/mk3.0appnoclean `pwd` mvlcge2.1.0 $a cross-$p /opt/mvlcge/rpmdb ~/.cgerpmrc rpm > /mvista/dev_area/logs/mvlcge2.1.0-updates/$p-$b/$a.log 2>&1
      fi
       mkdir -p /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/$a/cross/common
       mkdir -p /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/SRPMS
       cp -f SRPMS/* /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/SRPMS
       cp /home/build/cge-userland/$p/RPMS/noarch/*$a* /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/$a/cross/common
     elif [ "$type" = "target" ]; then
       if [ "$p" = "gcc" ]; then
       ~/bin/mk3.0appnoclean `pwd` mvlcge2.1.0 $a target-"$p"2.95.3 /opt/mvlcge/rpmdb ~/.cgerpmrc rpm > /mvista/dev_area/logs/mvlcge2.1.0-updates/$p-$b/$a.log 2>&1
       else
       ~/bin/mk3.0appnoclean `pwd` mvlcge2.1.0 $a target-$p /opt/mvlcge/rpmdb ~/.cgerpmrc rpm> /mvista/dev_area/logs/mvlcge2.1.0-updates/$p-$b/$a.log 2>&1
       fi	
       mkdir -p /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/$a/target
       mkdir -p /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/SRPMS
       cp -f /home/build/cge-userland/$p/SRPMS/* /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/SRPMS
       cp /home/build/cge-userland/$p/RPMS/$a/* /mvista/dev_area/mvlcge2.1.0-updates/$p-$b/$a/target
     fi
  done
done
