#!/bin/bash

if [ "$#" != "7" ]; then
  echo "Usage $0 <builddir> <build_id> <arch> <app name> <dbpath> <rcfile> <rpmbin>"
  exit
fi

builddir="$1"
buildid="$2"
arch="$3"
app="$4"
dbpath="$5"
rcfile="$6"
rpmbin="$7"

if [ -d "$builddir/SRPMS" ]; then
  rm -rf "$builddir/SRPMS"
fi
mkdir $builddir/SRPMS
if [ -d "$builddir/RPMS" ]; then
  rm -rf "$builddir/RPMS"
fi
mkdir $builddir/RPMS

if [ "$rpmbin" != "rpm" ]; then
  "$rpmbin"build -ba --define "_topdir $builddir" \
      --define "_hhl_build_id $buildid" \
      --define "vendor MontaVista Software, Inc." \
      --define "packager <source@mvista.com>" \
      --target=$arch-hardhat-linux $builddir/SPECS/hhl-*$app.spec --nodeps
else
  rpm -ba --define "_topdir $builddir" \
      --define "_hhl_build_id $buildid" \
      --define "vendor MontaVista Software, Inc." \
      --define "packager <source@mvista.com>" \
      --dbpath $dbpath \
      --rcfile $rcfile \
      --target=$arch-hardhat-linux $builddir/SPECS/hhl-*$app.spec
fi

