#!/bin/bash

if [ "$#" != "6" ]; then
  echo "Usage $0 <builddir> <build_id> <app name> <dbpath> <rcfile> <rpmbin>"
  exit
fi

builddir="$1"
buildid="$2"
app="$3"
dbpath="$4"
rcfile="$5"
rpmbin="$6"

if [ -d "$builddir/SRPMS" ]; then
  rm -rf "$builddir/SRPMS"
fi
mkdir $builddir/SRPMS
if [ -d "$builddir/RPMS" ]; then
  rm -rf "$builddir/RPMS"
fi
mkdir $builddir/RPMS

if [ "$rpmbin" = "rpm" ]; then
  rpm -ba --define "_topdir $builddir" \
    --define "_hhl_build_id $buildid" \
    --define "vendor MontaVista Software, Inc." \
    --define "packager <source@mvista.com>" \
    --dbpath $dbpath \
    --rcfile $rcfile \
    $builddir/SPECS/hhl-*$app.spec
else
  "$rpmbin"build -ba --define "_topdir $builddir" \
    --define "_hhl_build_id $buildid" \
    --define "vendor MontaVista Software, Inc." \
    --define "packager <source@mvista.com>" \
    $builddir/SPECS/hhl-*$app.spec --nodeps
fi
